import type { Metadata } from "next";
import "./globals.css";
import { MainPage } from "@/components/main-page";
import { NavbarPage } from "@/components/navbar-page";
import { Footer } from "@/components/footer";
import ScrollToTop from "@/components/ScrollToTop";

export const metadata: Metadata = {
  title: "Feed-galindoptbr.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-zinc-900 text-white">
        <MainPage />
        <NavbarPage />
        {children}
        <Footer />
        <ScrollToTop />
      </body>
    </html>
  );
}
